"""add users & organizations

Revision ID: 401a571dece3
Revises: f21c8279e777
Create Date: 2025-08-30 15:34:21.049361

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401a571dece3'
down_revision = 'f21c8279e777'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
