version: "3.9"

services:
  db:
    image: postgres:15
    container_name: multi_tenancy_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multi_tenancy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
